'use strict';

// ─── Reusable content fragments ───────────────────────────────────────────────

const BASE_URL = 'https://devravik.github.io';
const ASSETS = '/assets/attendassist';

const OFFLOAD = '100% offline, no account, zero ads, no subscriptions.';
const TRUST_BULLETS = [
  '100% offline - no internet required',
  'No account, no sign-up, no email, no cloud',
  'Free forever - no ads, no subscriptions',
  'Full data portability - export/import JSON',
];

const CTA_TEXT = 'Download Free on Play Store';

function pillarFeatures(category) {
  const map = {
    household: [
      { title: 'Individual Attendance', body: 'Daily check-in per staff member with status options - present, absent, leave, holiday, half-day, overtime. Background reminders if not marked.' },
      { title: 'Salary & Payments', body: 'Record salary, bonus, advance, and arrears. View complete payment history for each domestic helper.' },
      { title: 'Role-based Profiles', body: '14 pre-configured household roles - maid, cook, driver, nanny, gardener, watchman, and more. Add custom roles as needed.' },
      { title: 'Monthly Reports', body: 'Auto-generated monthly attendance summaries. Export to CSV for payroll calculation.' },
    ],
    attendance: [
      { title: 'Daily Status Tracking', body: 'Mark present, absent, leave, holiday, half-day, or overtime for any staff member. Quick single-tap entry.' },
      { title: 'Monthly Reports', body: 'View or share monthly attendance reports per person. CSV export for payroll processing.' },
      { title: 'Smart Reminders', body: 'Background notifications if attendance is not marked within 2+ hours of the usual arrival time.' },
      { title: 'Calendar View', body: 'Visual calendar showing daily status at a glance. Spot patterns and absences immediately.' },
    ],
    payroll: [
      { title: 'Salary Records', body: 'Store monthly salary for each staff member. Track bonus, advance, and arrears separately from base pay.' },
      { title: 'Payment History', body: 'Complete payment log with date, amount, and type. Search and filter by staff or date range.' },
      { title: 'Payroll Reports', body: 'View payroll summaries per person or across all staff. Export data for accounting.' },
      { title: 'Attendance Integration', body: 'Payroll and attendance are linked - see attendance records alongside payment history in one view.' },
    ],
    tenants: [
      { title: 'Monthly Rent Tracking', body: 'Record rent payments per tenant. Mark paid, pending, or partial. View yearly summaries at a glance.' },
      { title: 'Security Deposit', body: 'Track security deposit amounts. Know the deposit status for each tenant.' },
      { title: 'Tenant Profiles', body: 'Store tenant details, lease start date, rent amount, and payment history per person.' },
      { title: 'Yearly Summaries', body: 'See total rent collected per year, per tenant. Useful for tax filing and financial planning.' },
    ],
    classroom: [
      { title: 'Bulk Attendance', body: 'Mark attendance for the entire class at once. Supports roll numbers and student grouping.' },
      { title: 'Fee Collection', body: 'Track tuition fees per student. Record payments, partial payments, and pending amounts.' },
      { title: 'Student Profiles', body: 'Store student names, roll numbers, class, and contact details. Manage multiple classes.' },
      { title: 'Attendance Reports', body: 'View attendance records per student or per class. Export data for parent reporting.' },
    ],
    business: [
      { title: 'Employee Tracking', body: 'Monitor daily attendance for shop staff, warehouse workers, delivery personnel, and more.' },
      { title: 'Role Management', body: '26 ready-to-use business roles. Categorize employees by function and location.' },
      { title: 'Payroll Summary', body: 'Track wages and payments for each employee. View totals across the entire team.' },
      { title: 'Export & Reports', body: 'Export attendance and payroll data as CSV or JSON for accounting software.' },
    ],
    tools: [
      { title: 'Investment Calculators', body: 'SIP, Lumpsum, PPF, NPS, SWP, Goal Planner - plan your investments with precision.' },
      { title: 'Loan & EMI Tools', body: 'Home loan, car loan, bike loan, rent vs buy - compare and calculate EMIs instantly.' },
      { title: 'Savings Tools', body: 'Fixed Deposit, Recurring Deposit, Retirement calculator - project your savings growth.' },
      { title: 'Everyday Utilities', body: 'GST calculator, cash counter, unit converter, age calculator, date difference - tools you use daily.' },
    ],
  };
  return map[category] || map.attendance;
}

// ─── Core site pages ──────────────────────────────────────────────────────────

const CORE_PAGES = [
  {
    slug: 'features',
    title: 'All Features - AttendAssist: Attendance, Payroll, Rent & Classroom',
    description: 'Explore every AttendAssist feature: staff attendance tracking, payroll management, tenant rent collection, classroom management, and 28 free financial tools. All offline, private, and free.',
    h1: 'Every feature you need,<br>nothing you don\'t',
    sub: 'AttendAssist packs household management, attendance, payroll, rent tracking, classroom tools, and 28 calculators into one offline app. No accounts. No cloud. No cost.',
    features: [
      { title: 'Multi-Entity Support', body: 'Household staff, business employees, tenants, and students - manage all four from one app with dedicated interfaces per type.' },
      { title: 'Attendance Tracking', body: 'Daily check-in with present, absent, leave, holiday, half-day, overtime. Monthly CSV reports, calendar view, and smart reminders.' },
      { title: 'Payroll & Payments', body: 'Record salary, bonus, advance, arrears per person. Full payment history with search and filters.' },
      { title: 'Tenant Rent Management', body: 'Monthly rent tracking, security deposit logs, yearly summaries - built for landlords with multiple tenants.' },
      { title: 'Classroom Tools', body: 'Bulk attendance, fee collection, roll numbers, student profiles - designed for tutors and coaching centers.' },
      { title: '28 Financial Calculators', body: 'SIP, FD, EMI, GST, unit converter, salary calculator, and more - included at no additional cost.' },
    ],
    bullets: TRUST_BULLETS,
  },
  {
    slug: 'screenshots',
    title: 'Screenshots - AttendAssist App Tour',
    description: 'Browse screenshots of AttendAssist: dashboard, staff list, attendance calendar, payroll, tenant management, classroom, and 28 financial tools. See the app in action.',
    h1: 'See AttendAssist<br>in action',
    sub: 'Clean, warm interface. One primary action per screen. Browse the full app experience below.',
    features: [
      { title: 'Dashboard Overview', body: 'At-a-glance summary of today\'s attendance, recent payments, and quick actions.' },
      { title: 'Staff Management', body: 'Complete staff profiles with role, salary, attendance history, and payment records.' },
      { title: 'Attendance Calendar', body: 'Visual monthly calendar with color-coded status for each day.' },
      { title: 'Tenant Detail View', body: 'Per-tenant rent history, deposit tracking, and payment summaries.' },
      { title: 'Classroom Dashboard', body: 'Student list with bulk attendance, fee status, and roll number grouping.' },
      { title: 'Financial Tools Index', body: 'All 28 calculators in one scrollable grid - organized by category.' },
    ],
    bullets: TRUST_BULLETS,
  },
  {
    slug: 'faq',
    title: 'Frequently Asked Questions - AttendAssist',
    description: 'Common questions about AttendAssist: data privacy, offline usage, account requirements, exports, and supported features. Get answers fast.',
    h1: 'Frequently asked<br>questions',
    sub: 'Quick answers to the most common questions about AttendAssist.',
    features: [
      { title: 'Is AttendAssist really free?', body: 'Yes, completely free. No ads, no in-app purchases, no subscriptions. All features including the 28 financial tools are included at no cost.' },
      { title: 'Does it require internet?', body: 'No. AttendAssist works entirely offline. All data is stored locally on your device. No internet connection is needed for daily use.' },
      { title: 'Do I need to create an account?', body: 'No account needed. Install the app and start using it immediately. No email, no phone number, no sign-up.' },
      { title: 'Can I export my data?', body: 'Yes. Export all data as JSON or CSV. You can also import data from a previous installation when switching phones.' },
      { title: 'Is my data private?', body: 'Everything stays on your device using SQLite. No servers, no cloud sync, no data collection. Your information never leaves your phone.' },
      { title: 'What can I track?', body: 'Household staff (maids, cooks, drivers), business employees, tenants/rent, and classroom students. Plus 28 financial calculators.' },
    ],
    bullets: TRUST_BULLETS,
  },
  {
    slug: 'download',
    title: 'Download AttendAssist - Free Offline Attendance App',
    description: 'Download AttendAssist free on Google Play. Track staff attendance, payroll, rent, and classroom students. 100% offline. No account needed.',
    h1: 'Download AttendAssist<br>free on Play Store',
    sub: 'Start tracking attendance, payroll, rent, and classroom in under 30 seconds. No account. No internet. No cost.',
    features: [
      { title: 'Free Download', body: 'AttendAssist is free on the Google Play Store. No hidden charges, no in-app purchases, no subscription tiers.' },
      { title: 'Works Offline', body: 'Use the app anywhere - no internet connection required for any feature.' },
      { title: 'No Account Required', body: 'Install and start immediately. No sign-up, no email, no personal information needed.' },
      { title: 'Instant Setup', body: 'Add your first staff member or tenant in seconds. Pre-configured roles for household staff and business employees.' },
    ],
    bullets: TRUST_BULLETS,
  },
  {
    slug: 'privacy-first',
    title: 'Privacy First - AttendAssist Keeps Your Data on Your Phone',
    description: 'AttendAssist is built for privacy. No cloud, no servers, no tracking, no account. Your attendance, payroll, and tenant data stays on your device. Always.',
    h1: 'Privacy isn\'t a feature.<br>It\'s the foundation.',
    sub: 'AttendAssist never uploads your data anywhere. No servers. No cloud. No accounts. No tracking. What you type stays on your phone.',
    features: [
      { title: '100% On-Device', body: 'All data is stored in a local SQLite database on your phone. There are no servers to upload to.' },
      { title: 'No Account Needed', body: 'We don\'t ask for your email, phone number, or any personal information. No sign-up, ever.' },
      { title: 'No Tracking', body: 'No analytics SDK, no crash reporting, no ad trackers, no telemetry. The app makes zero network requests.' },
      { title: 'Full Data Control', body: 'Export your data as JSON and delete the app anytime. You own your data completely.' },
      { title: 'No Cloud Sync', body: 'Unlike most apps, there is no cloud sync - because there is no cloud. Your data is not stored on any server.' },
      { title: 'Open About Data', body: 'The app clearly shows what little data it stores. No fine print. No hidden data collection.' },
    ],
    bullets: [
      'Zero network requests',
      'No analytics or tracking',
      'No account or email required',
      'Full JSON data export',
    ],
  },
  {
    slug: 'offline-app',
    title: 'Best Offline Attendance App - AttendAssist (No Internet Needed)',
    description: 'AttendAssist is a fully offline attendance app. Track staff, tenants, and students without internet. No account, no cloud, completely free.',
    h1: 'Works everywhere.<br>Even without internet.',
    sub: 'AttendAssist is fully functional offline. Mark attendance, record payments, track rent, and run calculators - all without an internet connection.',
    features: [
      { title: 'Complete Offline Use', body: 'Every feature works offline - attendance, payroll, rent, classroom, and all 28 financial calculators. No internet access is ever required.' },
      { title: 'No Cloud Dependency', body: 'There are no servers. Your data is never uploaded anywhere. The app makes zero network calls.' },
      { title: 'Perfect for Remote Areas', body: 'Works in basements, rural areas, factories, construction sites - anywhere without reliable internet.' },
      { title: 'Install Once, Use Forever', body: 'Download the APK once from Play Store, then use the app indefinitely without ever connecting to the internet.' },
    ],
    bullets: [
      'Every feature works offline',
      'Zero network requests',
      'No cloud servers',
      'Works in remote areas',
    ],
  },
  {
    slug: 'free-app',
    title: 'Free Attendance App - AttendAssist (No Ads, No Subscriptions)',
    description: 'AttendAssist is a completely free attendance app. No ads, no subscriptions, no in-app purchases. Track staff, tenants, and classroom attendance at zero cost.',
    h1: 'Truly free.<br>No catches. No upsells.',
    sub: 'No ads. No subscriptions. No in-app purchases. No premium tiers. AttendAssist is free - every feature, forever.',
    features: [
      { title: 'Completely Free', body: 'Every feature is included at no cost. Attendance, payroll, rent tracking, classroom management, and 28 financial tools.' },
      { title: 'No Ads', body: 'There are no advertisements anywhere in the app. No banner ads, no full-screen ads, no sponsored content.' },
      { title: 'No Subscriptions', body: 'No monthly or yearly subscription. No premium tier. Free means free.' },
      { title: 'No In-App Purchases', body: 'There is nothing to buy. All tools and features are unlocked from the start.' },
    ],
    bullets: [
      'Zero cost',
      'No ads of any kind',
      'No subscriptions',
      'All features included',
    ],
  },
];

// ─── Household staff pages ────────────────────────────────────────────────────

const HOUSEHOLD_PAGES = [
  {
    slug: 'household-staff-attendance',
    title: 'Household Staff Attendance App - Track Maids, Cooks & Drivers',
    description: 'Track attendance for maids, cooks, drivers, nannies, gardeners, and more. Free offline household staff management app. No account needed.',
    h1: 'Track all your household staff<br>in one place',
    sub: 'Manage attendance and salary for maids, cooks, drivers, nannies, and other domestic helpers. ' + OFFLOAD,
    features: pillarFeatures('household'),
    bullets: TRUST_BULLETS,
  },
  {
    slug: 'maid-attendance-app',
    title: 'Maid Attendance App - Track Your Domestic Helper\'s Attendance',
    description: 'Free maid attendance tracker. Mark daily attendance, record salary payments, and view monthly reports. Offline, private, and easy to use.',
    h1: 'Maid attendance tracking<br>made simple',
    sub: 'Mark your maid\'s daily attendance, track salary payments, and generate monthly reports. All offline, all private.',
    features: [
      { title: 'Daily Attendance', body: 'Mark present, absent, leave, or holiday for your maid with a single tap. Status color-coded for quick scanning.' },
      { title: 'Salary Tracking', body: 'Record monthly salary, track payments, and view history. Know exactly what you\'ve paid and when.' },
      { title: 'Monthly Reports', body: 'Generate attendance and payment reports per month. Export as CSV for your records.' },
      { title: 'Smart Reminders', body: 'Optional reminders if attendance is not marked within 2+ hours of the typical arrival time.' },
    ],
    bullets: TRUST_BULLETS,
  },
  {
    slug: 'driver-attendance-app',
    title: 'Driver Attendance App - Track Your Driver\'s Hours & Attendance',
    description: 'Free driver attendance tracker. Mark daily attendance, log working hours, track salary. Offline. No account required.',
    h1: 'Driver attendance<br>and hours tracker',
    sub: 'Keep track of when your driver is on duty, mark attendance daily, and manage salary payments.',
    features: [
      { title: 'Daily Attendance', body: 'Quick attendance marking with status options. See at a glance if your driver was present this week.' },
      { title: 'Payment History', body: 'Log salary, bonus, and advance payments. Full searchable history per staff member.' },
      { title: 'Monthly Summaries', body: 'View monthly attendance percentage and total payments. Export data anytime.' },
      { title: 'Offline First', body: 'All features work without internet. No data charges, no connectivity issues.' },
    ],
    bullets: TRUST_BULLETS,
  },
  {
    slug: 'cook-attendance-app',
    title: 'Cook Attendance App - Free Kitchen Staff Attendance Tracker',
    description: 'Track your cook\'s attendance and salary with this free offline app. Mark daily presence, log payments, view reports. No account needed.',
    h1: 'Cook attendance<br>& salary tracker',
    sub: 'Know when your cook is on duty, track salary payments, and maintain records - all from your phone, offline.',
    features: [
      { title: 'Attendance Log', body: 'Quick daily check-in. View the weekly and monthly attendance pattern at a glance.' },
      { title: 'Salary Management', body: 'Set monthly salary, record payments, track advances. Complete payment trail for transparency.' },
      { title: 'Export Reports', body: 'Share attendance and payment reports as CSV for household accounting.' },
      { title: 'Zero Setup', body: 'Add your cook in seconds using the pre-configured household role. No complex setup required.' },
    ],
    bullets: TRUST_BULLETS,
  },
  {
    slug: 'nanny-attendance-app',
    title: 'Nanny Attendance App - Track Your Nanny\'s Schedule',
    description: 'Free nanny attendance tracker. Mark daily attendance, manage payments, and view schedules. Offline app for childcare staff management.',
    h1: 'Nanny attendance<br>& schedule tracker',
    sub: 'Track your nanny\'s daily attendance, manage payments, and maintain records - all in one offline app.',
    features: [
      { title: 'Daily Check-in', body: 'Mark present, absent, or leave. See your nanny\'s attendance pattern over days and weeks.' },
      { title: 'Payment Records', body: 'Log salary, advances, and bonuses. Keep a clean financial record for household budgeting.' },
      { title: 'Monthly View', body: 'Calendar-based view of attendance for any month. Quickly spot days off and patterns.' },
      { title: 'Private & Secure', body: 'All data stays on your phone. No cloud, no servers, no accounts.' },
    ],
    bullets: TRUST_BULLETS,
  },
  {
    slug: 'gardener-attendance-app',
    title: 'Gardener Attendance App - Free Garden Staff Tracker',
    description: 'Track your gardener\'s attendance with this free offline app. Mark daily presence, manage payments, and view reports.',
    h1: 'Gardener attendance<br>tracker',
    sub: 'Keep records of when your gardener works, track salary payments, and view attendance summaries.',
    features: [
      { title: 'Attendance Tracking', body: 'Mark daily attendance with status options. View attendance history by week or month.' },
      { title: 'Payment Log', body: 'Record salary payments, track advances, and view complete payment history.' },
      { title: 'Role Profile', body: 'Pre-configured gardener role with relevant defaults. Get started in seconds.' },
      { title: 'Data Export', body: 'Export all data as JSON or CSV. Full data portability.' },
    ],
    bullets: TRUST_BULLETS,
  },
  {
    slug: 'watchman-attendance-app',
    title: 'Watchman Attendance App - Track Security Staff Attendance',
    description: 'Free watchman attendance tracker. Mark daily presence for security guards, track shift attendance, manage payments. Offline app.',
    h1: 'Watchman attendance<br>& shift tracker',
    sub: 'Track when your security staff is on duty, manage payments, and view reports - all offline.',
    features: [
      { title: 'Daily Log', body: 'Mark attendance per shift. Track present, absent, leave, and overtime statuses.' },
      { title: 'Payment Management', body: 'Log salary, overtime pay, advances. Full history per watchman.' },
      { title: 'Monthly Reports', body: 'Generate monthly attendance and payment reports. Export as needed.' },
      { title: 'Offline Operation', body: 'Works without internet. No data costs, no connectivity dependence.' },
    ],
    bullets: TRUST_BULLETS,
  },
  {
    slug: 'domestic-helper-management',
    title: 'Domestic Helper Management App - All-in-One Household Staff Tool',
    description: 'Manage all your domestic helpers from one app. Track attendance, salary, and work history for maids, cooks, drivers, nannies. Free & offline.',
    h1: 'Complete domestic helper<br>management',
    sub: 'Manage attendance, salary, and work records for all your domestic staff. One app for maids, cooks, drivers, nannies, and more.',
    features: [
      { title: 'Multi-Staff Management', body: 'Add and manage multiple domestic helpers. Each with their own attendance and payment records.' },
      { title: 'Role-Based Setup', body: '14 pre-configured household roles. Select and go - no manual configuration needed.' },
      { title: 'Combined Dashboard', body: 'See attendance status for all helpers on one screen. Quick overview of today\'s status.' },
      { title: 'Individual Reports', body: 'Per-person monthly attendance and payment reports. Export individually or as a group.' },
    ],
    bullets: TRUST_BULLETS,
  },
  {
    slug: 'household-payroll',
    title: 'Household Payroll App - Manage Domestic Staff Salaries',
    description: 'Free household payroll app. Track salaries, bonuses, advances, and payments for maids, cooks, drivers, and nannies. Offline and private.',
    h1: 'Household payroll<br>made easy',
    sub: 'Track salaries, bonuses, advances, and arrears for all your domestic staff. Complete payment history at your fingertips.',
    features: [
      { title: 'Salary Management', body: 'Set monthly salary per staff member. Track base pay, bonuses, advances, and arrears separately.' },
      { title: 'Payment History', body: 'Complete log of every payment made. Search by staff, date range, or payment type.' },
      { title: 'Monthly Totals', body: 'View total household payroll cost per month. Useful for budgeting and expense tracking.' },
      { title: 'Export for Accounting', body: 'Export payroll data as CSV for use in spreadsheets or accounting software.' },
    ],
    bullets: TRUST_BULLETS,
  },
  {
    slug: 'manage-domestic-help',
    title: 'How to Manage Domestic Help - Free App for Household Staff',
    description: 'Learn how to manage domestic help effectively. Free app for tracking attendance, salary, and work records of household staff.',
    h1: 'Manage domestic help<br>the smart way',
    sub: 'Stop using paper registers and spreadsheets. Track attendance, salary, and work history for all your domestic staff from your phone.',
    features: [
      { title: 'Attendance Records', body: 'Maintain digital attendance records for every domestic helper. No more paper registers.' },
      { title: 'Salary Tracking', body: 'Keep clear salary records. Know what was paid, when, and to whom.' },
      { title: 'Work History', body: 'Build a complete work history for each staff member. Useful for reviews and reference.' },
      { title: 'Always Available', body: 'Records are always on your phone. No internet needed to access any data.' },
    ],
    bullets: TRUST_BULLETS,
  },
];

// ─── Attendance pages ─────────────────────────────────────────────────────────

const ATTENDANCE_PAGES = [
  {
    slug: 'staff-attendance-app',
    title: 'Staff Attendance App - Free Employee Attendance Tracker',
    description: 'Free staff attendance tracker app. Mark daily attendance for employees, household staff, or workers. Offline, no account, CSV export.',
    h1: 'Staff attendance tracking<br>for any team size',
    sub: 'Track attendance for employees, household staff, or workers. Mark daily status, view calendar, export monthly reports.',
    features: pillarFeatures('attendance'),
    bullets: TRUST_BULLETS,
  },
  {
    slug: 'employee-attendance-app',
    title: 'Employee Attendance App - Free Business Attendance Tracker',
    description: 'Free employee attendance app for small businesses. Track daily attendance, manage staff, and export reports. 100% offline.',
    h1: 'Employee attendance<br>tracker for businesses',
    sub: 'Track daily attendance for your employees. Mark present, absent, leave, overtime. Generate monthly reports.',
    features: pillarFeatures('attendance'),
    bullets: TRUST_BULLETS,
  },
  {
    slug: 'offline-attendance-app',
    title: 'Offline Attendance App - No Internet Required',
    description: 'Best offline attendance app. Works without internet. Track staff, students, and workers in remote areas. Free, no account needed.',
    h1: 'Works completely offline.<br>No internet. Ever.',
    sub: 'AttendAssist is fully functional offline. Mark attendance, manage payroll, track rent - all without an internet connection.',
    features: [
      { title: 'Fully Offline', body: 'Every feature works without internet. Mark attendance, view reports, manage payments - no connectivity needed.' },
      { title: 'No Servers', body: 'All data is stored locally on your device. There are no servers. Your data never leaves your phone.' },
      { title: 'Perfect for Remote Locations', body: 'Works anywhere - factories, farms, construction sites, rural areas, basement offices.' },
      { title: 'Sync-Free', body: 'No sync required. No waiting for data to upload. No cloud dependency.' },
    ],
    bullets: TRUST_BULLETS,
  },
  {
    slug: 'digital-attendance-register',
    title: 'Digital Attendance Register - Replace Your Paper Register',
    description: 'Replace your paper attendance register with a free digital app. Track attendance for staff, students, or workers. Offline, easy to use.',
    h1: 'Digital attendance register<br>for the modern workplace',
    sub: 'Replace paper registers and spreadsheets with a free digital attendance tracker. Faster, cleaner, always accessible.',
    features: [
      { title: 'Paperless Records', body: 'Stop maintaining paper attendance registers. Digital records are cleaner, searchable, and never lost.' },
      { title: 'One-Tap Marking', body: 'Mark attendance with a single tap. No writing names, no manual calculations.' },
      { title: 'Auto-Generated Reports', body: 'Monthly attendance reports generated automatically. No manual tallying.' },
      { title: 'CSV Export', body: 'Export attendance data as CSV for payroll processing or record keeping.' },
    ],
    bullets: TRUST_BULLETS,
  },
  {
    slug: 'attendance-tracker',
    title: 'Attendance Tracker App - Free Daily Attendance Log',
    description: 'Free daily attendance tracker. Mark who is present, absent, on leave, or overtime. View monthly reports. Offline and private.',
    h1: 'Simple attendance tracker<br>for everyday use',
    sub: 'A clean, simple way to track who is present each day. Tap to mark, scroll to review, export when needed.',
    features: [
      { title: 'Quick Marking', body: 'Tap to cycle through statuses: present, absent, leave, holiday, half-day, overtime.' },
      { title: 'Daily Overview', body: 'See who\'s in and who\'s not - all on one screen. Color-coded for instant understanding.' },
      { title: 'Monthly Calendar', body: 'Calendar view for any month shows attendance patterns at a glance.' },
      { title: 'Report Export', body: 'Generate and share monthly attendance reports as CSV.' },
    ],
    bullets: TRUST_BULLETS,
  },
  {
    slug: 'attendance-report-generator',
    title: 'Attendance Report Generator - Auto-Generate Monthly Reports',
    description: 'Free attendance report generator. Auto-generate monthly attendance reports with present, absent, leave counts. Export CSV.',
    h1: 'Generate attendance reports<br>instantly',
    sub: 'Stop tallying attendance manually. AttendAssist generates monthly reports automatically with one tap.',
    features: [
      { title: 'Auto-Generated Reports', body: 'Monthly attendance reports with present, absent, leave, holiday, and overtime counts per person.' },
      { title: 'Per-Person Reports', body: 'View attendance summary for each staff member individually. See trends over time.' },
      { title: 'CSV Export', body: 'Export any report as CSV. Open in Excel, Google Sheets, or import into accounting software.' },
      { title: 'Date Range Filter', body: 'Generate reports for custom date ranges, not just full months.' },
    ],
    bullets: TRUST_BULLETS,
  },
  {
    slug: 'monthly-attendance-report',
    title: 'Monthly Attendance Report - Free Auto-Generated Reports',
    description: 'Get monthly attendance reports automatically. See present days, absences, leaves, and overtime. Free offline app.',
    h1: 'Monthly attendance reports<br>without the math',
    sub: 'Let the app do the counting. Monthly attendance reports with every stat you need.',
    features: [
      { title: 'Full Month Summary', body: 'Present, absent, leave, holiday, half-day, overtime - all counted and displayed per person.' },
      { title: 'Visual Calendar', body: 'At-a-glance calendar view showing the status for every day of the month.' },
      { title: 'Shareable Reports', body: 'Share reports via email, WhatsApp, or any app. Export as CSV for payroll.' },
      { title: 'Year-to-Date View', body: 'See attendance trends across months. Spot patterns in absences or overtime.' },
    ],
    bullets: TRUST_BULLETS,
  },
  {
    slug: 'csv-attendance-export',
    title: 'CSV Attendance Export - Export Attendance Data for Payroll',
    description: 'Export attendance data as CSV from AttendAssist. Use in Excel, Google Sheets, or payroll software. Free and offline.',
    h1: 'Export attendance<br>to CSV in one tap',
    sub: 'Take your attendance data anywhere. CSV export works with Excel, Google Sheets, and payroll software.',
    features: [
      { title: 'One-Tap Export', body: 'Export all attendance data as CSV with a single tap. No conversion steps needed.' },
      { title: 'Payroll Ready', body: 'CSV format is compatible with payroll software, Excel, and Google Sheets.' },
      { title: 'Per-Person or Group', body: 'Export individual attendance or all staff at once. Filter by date range.' },
      { title: 'Full Data Portability', body: 'Take your data anywhere. CSV is the universal format for data exchange.' },
    ],
    bullets: TRUST_BULLETS,
  },
];

// ─── Payroll pages ────────────────────────────────────────────────────────────

const PAYROLL_PAGES = [
  {
    slug: 'payroll-management',
    title: 'Payroll Management App - Free Staff Payment Tracker',
    description: 'Free payroll management app for small businesses and households. Track salaries, bonuses, advances, and payment history. Offline.',
    h1: 'Payroll management<br>for small teams',
    sub: 'Track salaries, bonuses, advances, and arrears for your staff. Complete payment history with CSV export.',
    features: pillarFeatures('payroll'),
    bullets: TRUST_BULLETS,
  },
  {
    slug: 'staff-payment-tracker',
    title: 'Staff Payment Tracker - Free Salary & Payment Log',
    description: 'Free staff payment tracker app. Log salary payments, bonuses, and advances. View complete payment history per employee.',
    h1: 'Track staff payments<br>with zero effort',
    sub: 'Log every salary payment, bonus, and advance. Know exactly what you\'ve paid and when.',
    features: [
      { title: 'Payment Log', body: 'Record each payment with date, amount, and type. Search and filter by staff member.' },
      { title: 'Salary Records', body: 'Store monthly salary per person. Track changes over time.' },
      { title: 'Bonus & Advances', body: 'Separate tracking for bonuses, advances, and arrears. Not mixed with base salary.' },
      { title: 'Payment History', body: 'Complete payment history for each staff member. Useful for reference and disputes.' },
    ],
    bullets: TRUST_BULLETS,
  },
  {
    slug: 'salary-tracker',
    title: 'Salary Tracker App - Track Employee Salaries & Payments',
    description: 'Free salary tracker. Record monthly salaries, log payments, track advances. Offline app for small business payroll.',
    h1: 'Salary tracker<br>for small business',
    sub: 'Keep track of employee salaries, payment dates, and outstanding amounts. All offline and private.',
    features: [
      { title: 'Set Monthly Salary', body: 'Store the agreed monthly salary for each employee. Reference it when making payments.' },
      { title: 'Payment History', body: 'Every payment, bonus, and advance is logged with date and amount.' },
      { title: 'Outstanding View', body: 'See at a glance if a month\'s salary is pending or paid.' },
      { title: 'Export Records', body: 'Export salary records as CSV for accounting or tax filing.' },
    ],
    bullets: TRUST_BULLETS,
  },
  {
    slug: 'employee-payroll-app',
    title: 'Employee Payroll App - Free Small Business Payroll',
    description: 'Free employee payroll app for small businesses. Track employee salaries, bonuses, and payment history. Works offline.',
    h1: 'Employee payroll<br>made simple',
    sub: 'Manage payroll for your employees without spreadsheets. Track salary, bonuses, advances, and payment history.',
    features: pillarFeatures('payroll'),
    bullets: TRUST_BULLETS,
  },
  {
    slug: 'salary-payment-history',
    title: 'Salary Payment History - View Complete Pay Records',
    description: 'View complete salary payment history for every employee or staff member. Search, filter, and export. Free offline app.',
    h1: 'Complete salary payment<br>history at your fingertips',
    sub: 'Every payment recorded, searchable, and exportable. Never lose track of who was paid what.',
    features: [
      { title: 'Full History', body: 'Every salary payment, bonus, advance, and arrears recorded with date and amount.' },
      { title: 'Search & Filter', body: 'Search by staff member, date range, or payment type. Find any record instantly.' },
      { title: 'Per-Person View', body: 'See the complete payment timeline for any staff member. Know the total paid.' },
      { title: 'Export Any Report', body: 'Export payment history as CSV for accounting or personal records.' },
    ],
    bullets: TRUST_BULLETS,
  },
  {
    slug: 'payroll-with-attendance',
    title: 'Payroll with Attendance - Integrated Attendance & Payroll App',
    description: 'Integrated attendance and payroll app. Link attendance records with salary payments. Free offline app for small business.',
    h1: 'Attendance and payroll<br>in one place',
    sub: 'See attendance records alongside payment history. Make informed payroll decisions with complete context.',
    features: [
      { title: 'Linked Records', body: 'Attendance and payroll are integrated. View both on the same profile for each staff member.' },
      { title: 'Context-Rich Payroll', body: 'See attendance patterns when reviewing payroll. Know if absences align with payment changes.' },
      { title: 'Combined Reports', body: 'Generate reports that include both attendance and payment data for the same period.' },
      { title: 'Simplified Workflow', body: 'One app for both attendance and payroll. No switching between tools.' },
    ],
    bullets: TRUST_BULLETS,
  },
];

// ─── Tenant & Rent pages ──────────────────────────────────────────────────────

const TENANT_PAGES = [
  {
    slug: 'rent-management-app',
    title: 'Rent Management App - Free Rent Collection Tracker',
    description: 'Free rent management app for landlords. Track monthly rent payments, security deposits, and tenant history. Offline and private.',
    h1: 'Rent management<br>for landlords',
    sub: 'Track monthly rent, security deposits, and payment history for all your tenants. Offline, private, and free.',
    features: pillarFeatures('tenants'),
    bullets: TRUST_BULLETS,
  },
  {
    slug: 'tenant-management-app',
    title: 'Tenant Management App - Free Landlord Tool',
    description: 'Free tenant management app. Track tenant details, rent payments, security deposits, and lease information. Offline.',
    h1: 'Tenant management<br>for every landlord',
    sub: 'Keep detailed records for each tenant: rent payments, deposits, lease dates, and contact information.',
    features: [
      { title: 'Tenant Profiles', body: 'Store tenant name, contact, lease start date, monthly rent, and security deposit amount.' },
      { title: 'Rent Payment Log', body: 'Record monthly payments. Mark paid, pending, or partial. View history per tenant.' },
      { title: 'Security Deposit', body: 'Track deposit amounts and status. Know what was collected and what needs to be returned.' },
      { title: 'Yearly Summaries', body: 'View total rent collected per year per tenant. Useful for tax filing.' },
    ],
    bullets: TRUST_BULLETS,
  },
  {
    slug: 'rent-collection-tracker',
    title: 'Rent Collection Tracker - Free Monthly Rent Log',
    description: 'Free rent collection tracker app. Log monthly rent payments, track pending amounts, and view collection history.',
    h1: 'Rent collection tracker<br>for hassle-free tracking',
    sub: 'Never lose track of who has paid rent and who hasn\'t. Simple, visual, and always up to date.',
    features: [
      { title: 'Monthly Tracking', body: 'Mark rent as paid, pending, or partial for each month. See the status at a glance.' },
      { title: 'Per-Tenant View', body: 'View the complete payment history for any tenant. Know the total collected.' },
      { title: 'Overdue Alerts', body: 'See at a glance which tenants have pending payments and for how long.' },
      { title: 'Yearly Summary', body: 'Annual rent collection summary. Useful for financial planning and tax filing.' },
    ],
    bullets: TRUST_BULLETS,
  },
  {
    slug: 'rental-property-management',
    title: 'Rental Property Management App - Free Landlord Software',
    description: 'Free rental property management app. Track rent, tenants, security deposits, and property details. Offline and easy to use.',
    h1: 'Rental property management<br>from your phone',
    sub: 'Manage your rental properties and tenants from one app. Track rent, deposits, and tenant records.',
    features: [
      { title: 'Multi-Property Ready', body: 'Manage multiple properties and tenants from a single app. Each tenant has their own records.' },
      { title: 'Rent Dashboard', body: 'See all rent payments across tenants on one screen. Know your total rental income.' },
      { title: 'Deposit Tracking', body: 'Record and track security deposits per tenant. Know the status of each deposit.' },
      { title: 'Export for Taxes', body: 'Export rental income data as CSV for tax filing and financial records.' },
    ],
    bullets: TRUST_BULLETS,
  },
  {
    slug: 'landlord-rent-tracker',
    title: 'Landlord Rent Tracker - Free App for Property Owners',
    description: 'Free rent tracker for landlords. Log monthly rent, track payments, and manage multiple tenants. Offline app.',
    h1: 'Landlord rent tracker<br>for property owners',
    sub: 'Track rent payments across all your tenants. Simple, reliable, and completely free.',
    features: [
      { title: 'Multi-Tenant Tracking', body: 'Track rent for all your tenants in one place. Each with independent payment history.' },
      { title: 'Payment Status', body: 'Green for paid, red for pending, yellow for partial. Instant visual status.' },
      { title: 'Annual Reports', body: 'Year-end summary showing total rent collected per property or tenant.' },
      { title: 'Data Portability', body: 'Export all rental data as JSON or CSV. Switch phones without losing records.' },
    ],
    bullets: TRUST_BULLETS,
  },
  {
    slug: 'security-deposit-tracker',
    title: 'Security Deposit Tracker - Track Rental Deposits',
    description: 'Free security deposit tracker. Record deposit amounts per tenant, track status, and manage returns. Offline app.',
    h1: 'Security deposit tracker<br>for landlords',
    sub: 'Keep track of security deposits collected from each tenant. Know the amount and status at all times.',
    features: [
      { title: 'Deposit Records', body: 'Record the security deposit amount for each tenant. Store alongside their rent records.' },
      { title: 'Deposit Status', body: 'Track whether the deposit is active, partially returned, or fully returned.' },
      { title: 'Linked to Tenant', body: 'Deposits are linked to tenant profiles. See deposit and rent history together.' },
      { title: 'Reference Data', body: 'Access deposit information instantly when tenants move out or request returns.' },
    ],
    bullets: TRUST_BULLETS,
  },
  {
    slug: 'tenant-payment-history',
    title: 'Tenant Payment History - View Complete Rent Records',
    description: 'View complete rent payment history for each tenant. Track paid, pending, and partial months. Free offline app.',
    h1: 'Tenant payment history<br>at your fingertips',
    sub: 'Complete rent payment history for every tenant. Every payment, every status, always accessible.',
    features: [
      { title: 'Full History', body: 'Every month\'s rent status recorded. Know exactly when each payment was made.' },
      { title: 'Per-Tenant Timeline', body: 'Scroll through months of payment history per tenant. Spot patterns and gaps.' },
      { title: 'Payment Proof', body: 'Record payment dates as proof of collection. Useful for financial records.' },
      { title: 'Export Records', body: 'Export tenant payment history as CSV for tax filing or accounting.' },
    ],
    bullets: TRUST_BULLETS,
  },
];

// ─── Classroom pages ──────────────────────────────────────────────────────────

const CLASSROOM_PAGES = [
  {
    slug: 'classroom-management-app',
    title: 'Classroom Management App - Free for Tutors & Coaches',
    description: 'Free classroom management app for tutors and coaching centers. Track attendance, fees, and student records. Offline.',
    h1: 'Classroom management<br>for tutors & coaches',
    sub: 'Track student attendance, collect fees, and manage class records. Built for tutors, coaching centers, and small classes.',
    features: pillarFeatures('classroom'),
    bullets: TRUST_BULLETS,
  },
  {
    slug: 'student-attendance-app',
    title: 'Student Attendance App - Free Class Attendance Tracker',
    description: 'Free student attendance tracker. Mark bulk attendance, track per-student records, and export reports. Offline app.',
    h1: 'Student attendance<br>tracker for teachers',
    sub: 'Mark attendance for the entire class at once. Track per-student attendance and generate reports.',
    features: [
      { title: 'Bulk Attendance', body: 'Mark attendance for all students at once. Select status and apply to the entire class.' },
      { title: 'Per-Student Records', body: 'View attendance history for any individual student. Track patterns over time.' },
      { title: 'Roll Numbers', body: 'Assign roll numbers to students. Sort and display by roll number for easy marking.' },
      { title: 'Attendance Reports', body: 'Generate class-wide or per-student attendance reports. Export as needed.' },
    ],
    bullets: TRUST_BULLETS,
  },
  {
    slug: 'tuition-fee-tracker',
    title: 'Tuition Fee Tracker - Free Fee Collection App for Tutors',
    description: 'Free tuition fee tracker for tutors. Record fee payments, track pending amounts, and manage student fee history.',
    h1: 'Tuition fee tracker<br>for independent tutors',
    sub: 'Keep track of who has paid tuition fees and who hasn\'t. Simple, visual, and always on your phone.',
    features: [
      { title: 'Fee Records', body: 'Record fee payments per student. Mark as paid, pending, or partial.' },
      { title: 'Per-Student History', body: 'View complete fee payment history for each student. Know the total collected.' },
      { title: 'Monthly Overview', body: 'See fee collection status for the entire class in one view.' },
      { title: 'Export for Records', body: 'Export fee data as CSV for your financial records.' },
    ],
    bullets: TRUST_BULLETS,
  },
  {
    slug: 'coaching-center-management',
    title: 'Coaching Center Management App - Free for Small Institutes',
    description: 'Free coaching center management app. Track student attendance, fees, and class schedules. Offline and easy to use.',
    h1: 'Coaching center<br>management made simple',
    sub: 'Manage your coaching center\'s students, attendance, and fees from one app. No internet needed.',
    features: [
      { title: 'Student Management', body: 'Add students with name, roll number, class, and contact. Organize by class or batch.' },
      { title: 'Bulk Attendance', body: 'Mark attendance for the entire batch in one go. Save time during busy class transitions.' },
      { title: 'Fee Collection', body: 'Track tuition fee payments per student. View collection status at a glance.' },
      { title: 'Attendance Reports', body: 'Generate attendance reports per student or per class. Share with parents on request.' },
    ],
    bullets: TRUST_BULLETS,
  },
  {
    slug: 'coaching-center-attendance',
    title: 'Coaching Center Attendance - Free Batch Attendance Tracker',
    description: 'Free attendance tracker for coaching centers. Mark batch attendance, track student records, and export reports.',
    h1: 'Coaching center attendance<br>tracker',
    sub: 'Track attendance for multiple batches and classes. Bulk marking, per-student records, and auto-generated reports.',
    features: [
      { title: 'Batch Attendance', body: 'Mark attendance for entire batches. Switch between classes easily.' },
      { title: 'Individual Tracking', body: 'View attendance history per student across all sessions.' },
      { title: 'Absence Reports', body: 'Quickly see which students have high absence rates over any period.' },
      { title: 'Export & Share', body: 'Export attendance reports as CSV. Share with parents or administration.' },
    ],
    bullets: TRUST_BULLETS,
  },
  {
    slug: 'student-fee-management',
    title: 'Student Fee Management - Free Tuition Fee Tracker',
    description: 'Free student fee management app for tutors. Record payments, track dues, and view fee collection history.',
    h1: 'Student fee management<br>for tutors',
    sub: 'Track who has paid, who hasn\'t, and what\'s due. Clean fee management for small classes.',
    features: [
      { title: 'Payment Tracking', body: 'Record each fee payment with date and amount. Mark as full or partial.' },
      { title: 'Due Alerts', body: 'See at a glance which students have pending fees and for how long.' },
      { title: 'Monthly Collection', body: 'View total fees collected per month. Know your monthly income.' },
      { title: 'Student History', body: 'Complete fee payment history per student. Useful for parent communication.' },
    ],
    bullets: TRUST_BULLETS,
  },
  {
    slug: 'tutor-attendance-app',
    title: 'Tutor Attendance App - Free for Private Tutors',
    description: 'Free attendance app for private tutors. Track student attendance, log fees, and manage class records. Offline.',
    h1: 'Attendance app<br>for private tutors',
    sub: 'Track which students attended each session. Log fees, manage records - all from your phone.',
    features: [
      { title: 'Session Attendance', body: 'Mark attendance for each tutoring session. See who was present and who missed.' },
      { title: 'Fee Logging', body: 'Record fee payments alongside attendance. Keep everything in one place.' },
      { title: 'Student Notes', body: 'Add notes per student. Track progress, concerns, or topics covered.' },
      { title: 'Simple & Fast', body: 'Mark a class in under 10 seconds. More time teaching, less time admin.' },
    ],
    bullets: TRUST_BULLETS,
  },
  {
    slug: 'bulk-student-attendance',
    title: 'Bulk Student Attendance - Mark Full Class in One Tap',
    description: 'Free bulk student attendance app. Mark attendance for the entire class at once. Perfect for coaching centers and schools.',
    h1: 'Bulk student attendance<br>in one tap',
    sub: 'Mark attendance for the entire class simultaneously. Then adjust individual records if needed.',
    features: [
      { title: 'One-Tap Class Marking', body: 'Select all students and mark them present, absent, or leave with one tap.' },
      { title: 'Individual Override', body: 'After bulk marking, adjust individual students who have different status.' },
      { title: 'Roll Number Display', body: 'Students displayed with roll numbers for quick visual scanning.' },
      { title: 'Daily Log', body: 'Each day\'s attendance logged with date and class. Full history maintained.' },
    ],
    bullets: TRUST_BULLETS,
  },
];

// ─── Small business pages ─────────────────────────────────────────────────────

const BUSINESS_PAGES = [
  {
    slug: 'small-business-attendance',
    title: 'Small Business Attendance App - Free Employee Tracker',
    description: 'Free small business attendance app. Track employee attendance, manage payroll, and export reports. Offline and easy to use.',
    h1: 'Small business attendance<br>& payroll tracker',
    sub: 'Track attendance and payroll for your small business employees. No expensive software needed.',
    features: pillarFeatures('business'),
    bullets: TRUST_BULLETS,
  },
  {
    slug: 'shop-employee-management',
    title: 'Shop Employee Management - Free Retail Staff Tracker',
    description: 'Free app for managing shop employees. Track attendance, manage shifts, and handle payroll for retail staff.',
    h1: 'Shop employee management<br>for retail owners',
    sub: 'Track attendance, manage schedules, and handle payroll for your retail staff. All from your phone.',
    features: [
      { title: 'Staff Attendance', body: 'Mark daily attendance for each shop employee. See who is working today.' },
      { title: 'Role Management', body: 'Assign roles like cashier, sales, stock, or manager. Organize by department.' },
      { title: 'Payroll Tracking', body: 'Record salaries and payments per employee. View total payroll costs.' },
      { title: 'Offline Operation', body: 'Works in shops and stores without reliable internet. No connectivity issues.' },
    ],
    bullets: TRUST_BULLETS,
  },
  {
    slug: 'employee-tracker',
    title: 'Employee Tracker App - Free Staff Attendance & Payroll',
    description: 'Free employee tracker app. Monitor staff attendance, track work schedules, and manage payroll. 100% offline.',
    h1: 'Employee tracker<br>for small teams',
    sub: 'Track who is working, when they are working, and what they are paid. All in one offline app.',
    features: [
      { title: 'Daily Attendance', body: 'Mark employees as present, absent, on leave, or overtime. Daily log maintained.' },
      { title: 'Schedule View', body: 'See the entire team\'s attendance status on one screen.' },
      { title: 'Payment Records', body: 'Track salaries, bonuses, and advances for each employee.' },
      { title: 'Export for Accounting', body: 'Export attendance and payroll data as CSV for your accountant.' },
    ],
    bullets: TRUST_BULLETS,
  },
  {
    slug: 'delivery-staff-attendance',
    title: 'Delivery Staff Attendance - Free Delivery Boy Tracker',
    description: 'Free delivery staff attendance tracker. Mark daily attendance for delivery personnel, track payments, and manage records.',
    h1: 'Delivery staff attendance<br>& payment tracker',
    sub: 'Track when your delivery staff is on duty and manage their payments. Simple, offline, free.',
    features: [
      { title: 'Daily Check-In', body: 'Mark delivery staff as present, on delivery, or absent. Track working days.' },
      { title: 'Payment Tracking', body: 'Record daily wages, bonuses, and advances. Complete payment history per person.' },
      { title: 'Attendance Reports', body: 'Monthly attendance summaries per delivery staff. Export for payroll.' },
      { title: 'Quick Setup', body: 'Add delivery staff with pre-configured business roles. Start in seconds.' },
    ],
    bullets: TRUST_BULLETS,
  },
  {
    slug: 'warehouse-worker-attendance',
    title: 'Warehouse Worker Attendance - Free Factory Staff Tracker',
    description: 'Free warehouse worker attendance app. Track factory and warehouse staff attendance. Works offline in industrial areas.',
    h1: 'Warehouse worker attendance<br>tracker',
    sub: 'Track attendance for warehouse and factory workers. Works in areas with no internet connectivity.',
    features: [
      { title: 'Industrial Use', body: 'Built for warehouses, factories, and industrial settings. Works completely offline.' },
      { title: 'Shift Tracking', body: 'Track multiple shifts per day. Mark attendance per shift for each worker.' },
      { title: 'Workforce Overview', body: 'See how many workers are present across all shifts at a glance.' },
      { title: 'Payroll Integration', body: 'Attendance records feed into payment tracking. Know who to pay for what.' },
    ],
    bullets: TRUST_BULLETS,
  },
  {
    slug: 'employee-management-app',
    title: 'Employee Management App - Free All-in-One Staff Tool',
    description: 'Free employee management app. Track attendance, payroll, and staff records. Perfect for small businesses. Offline.',
    h1: 'Employee management<br>for growing businesses',
    sub: 'Manage your team\'s attendance, payroll, and records from your phone. No expensive HR software needed.',
    features: [
      { title: 'Complete Staff Records', body: 'Store employee details, role, salary, and contact information. All in one place.' },
      { title: 'Attendance & Payroll', body: 'Integrated attendance and payroll. See the full picture for each employee.' },
      { title: 'Team Overview', body: 'Dashboard showing your entire team\'s attendance status for today.' },
      { title: 'Data Export', body: 'Export employee attendance and payroll data for accounting or tax purposes.' },
    ],
    bullets: TRUST_BULLETS,
  },
];

// ─── Financial tools pages ────────────────────────────────────────────────────

const TOOL_PAGES = [
  {
    slug: 'financial-calculators',
    title: '28 Free Financial Calculators - AttendAssist Tools',
    description: '28 free financial calculators in AttendAssist: SIP, FD, EMI, GST, unit converter, salary calculator, and more. All offline, all free.',
    h1: '28 financial calculators.<br>Included free.',
    sub: 'SIP, FD, EMI, GST, unit converter, salary calculator, and more - usually sold as separate apps, included in AttendAssist at no cost.',
    features: pillarFeatures('tools'),
    bullets: TRUST_BULLETS,
  },
  {
    slug: 'sip-calculator',
    title: 'SIP Calculator - Free Systematic Investment Plan Calculator',
    description: 'Free SIP calculator. Calculate monthly SIP returns, future value, and investment growth. Offline calculator in AttendAssist.',
    h1: 'SIP calculator<br>for investment planning',
    sub: 'Calculate monthly SIP returns, projected corpus, and investment growth. Free, instant, offline.',
    features: [
      { title: 'Monthly SIP Returns', body: 'Calculate the future value of your monthly SIP investments. Adjust amount, tenure, and expected returns.' },
      { title: 'Target Corpus', body: 'Work backwards from a target amount to find the monthly SIP needed.' },
      { title: 'Growth Visualization', body: 'See how your investment grows over time with clear projections.' },
      { title: 'No Internet Needed', body: 'All calculations run on your device. No server calls, no data sharing.' },
    ],
    bullets: TRUST_BULLETS,
  },
  {
    slug: 'emi-calculator',
    title: 'EMI Calculator - Free Loan EMI Calculator',
    description: 'Free EMI calculator. Calculate monthly EMI for home loan, car loan, bike loan, and personal loan. Offline.',
    h1: 'EMI calculator<br>for any loan',
    sub: 'Calculate monthly EMI, total interest, and payment schedule for any loan type.',
    features: [
      { title: 'All Loan Types', body: 'Home loan, car loan, bike loan, personal loan - calculate EMI for any loan type.' },
      { title: 'Detailed Breakdown', body: 'See principal, interest, and total payment. Monthly or yearly amortization.' },
      { title: 'Compare Loans', body: 'Compare EMI across different loan amounts, tenures, and interest rates.' },
      { title: 'Instant Results', body: 'Results update instantly as you adjust sliders. No button clicking needed.' },
    ],
    bullets: TRUST_BULLETS,
  },
  {
    slug: 'gst-calculator',
    title: 'GST Calculator - Free Goods & Services Tax Calculator',
    description: 'Free GST calculator. Calculate GST amounts, inclusive/exclusive prices, and tax breakdowns. Offline.',
    h1: 'GST calculator<br>for businesses',
    sub: 'Calculate GST inclusive and exclusive prices. Supports all GST rates.',
    features: [
      { title: 'GST Inclusive/Exclusive', body: 'Calculate price before and after GST. Works both ways.' },
      { title: 'All GST Rates', body: 'Supports 5%, 12%, 18%, and 28% GST rates. Select and calculate instantly.' },
      { title: 'Tax Breakdown', body: 'See the split between CGST and SGST for each calculation.' },
      { title: 'Business Ready', body: 'Perfect for invoicing, quoting, and tax filing preparation.' },
    ],
    bullets: TRUST_BULLETS,
  },
  {
    slug: 'fd-calculator',
    title: 'FD Calculator - Free Fixed Deposit Calculator',
    description: 'Free FD calculator. Calculate fixed deposit maturity amount and interest earned. Offline.',
    h1: 'Fixed deposit<br>calculator',
    sub: 'Calculate FD maturity amount, interest earned, and effective yield. Simple and compound interest.',
    features: [
      { title: 'Maturity Amount', body: 'Calculate the maturity amount for any fixed deposit. Adjust principal, rate, and tenure.' },
      { title: 'Interest Earned', body: 'See total interest earned over the deposit period.' },
      { title: 'Compound Interest', body: 'Supports quarterly, half-yearly, and yearly compounding.' },
      { title: 'Quick Comparison', body: 'Compare returns across different tenures and interest rates.' },
    ],
    bullets: TRUST_BULLETS,
  },
  {
    slug: 'unit-converter',
    title: 'Unit Converter - Free All-in-One Unit Conversion Tool',
    description: 'Free unit converter app. Convert length, weight, temperature, area, volume, and more. Offline.',
    h1: 'Unit converter<br>for everyday use',
    sub: 'Convert between units for length, weight, temperature, area, volume, and more. All offline.',
    features: [
      { title: 'Multiple Categories', body: 'Length, weight, temperature, area, volume, speed, and more categories.' },
      { title: 'All Common Units', body: 'Metric, imperial, and specialized units. Hundreds of conversion pairs.' },
      { title: 'Instant Conversion', body: 'Results update as you type. No button pressing required.' },
      { title: 'Offline Use', body: 'All conversion factors are built into the app. No internet needed.' },
    ],
    bullets: TRUST_BULLETS,
  },
  {
    slug: 'salary-calculator',
    title: 'Salary Calculator - Free Take-Home Salary Calculator',
    description: 'Free salary calculator. Calculate take-home salary, in-hand amount, and tax deductions. Offline.',
    h1: 'Salary calculator<br>for employees',
    sub: 'Calculate your take-home salary, in-hand amount, and deductions. Free and offline.',
    features: [
      { title: 'Take-Home Salary', body: 'Calculate in-hand salary after deductions. Know what hits your bank account.' },
      { title: 'CTC Breakdown', body: 'Break down the CTC into components: basic, HRA, allowances, deductions.' },
      { title: 'Tax Estimation', body: 'Estimate income tax based on salary components.' },
      { title: 'Quick Results', body: 'Enter your CTC and get the breakdown instantly.' },
    ],
    bullets: TRUST_BULLETS,
  },
];

// ─── Comparison pages ─────────────────────────────────────────────────────────

const COMPARISON_PAGES = [
  {
    slug: 'vs-excel',
    title: 'AttendAssist vs Excel - Why Use a Dedicated Attendance App',
    description: 'Compare AttendAssist vs Excel for attendance tracking. See why a dedicated app is faster, easier, and more reliable than spreadsheets.',
    h1: 'AttendAssist vs Excel<br>Why use a dedicated app?',
    sub: 'Excel is powerful, but it\'s not built for daily attendance tracking. Here\'s why AttendAssist is better.',
    features: [
      { title: 'One-Tap Marking', body: 'Excel: Open file, find the right row, type status. AttendAssist: One tap to mark present or absent.' },
      { title: 'Auto-Generated Reports', body: 'Excel: Manual formulas and pivot tables. AttendAssist: Monthly reports generated automatically.' },
      { title: 'No Setup Required', body: 'Excel: Create columns, set up formulas, format cells. AttendAssist: Install and start immediately.' },
      { title: 'On Your Phone', body: 'Excel: Awkward on mobile. AttendAssist: Built for phone-first daily use.' },
      { title: 'Data Integrity', body: 'Excel: Easy to accidentally edit or delete records. AttendAssist: Structured data that stays clean.' },
      { title: 'Offline by Design', body: 'Both work offline, but AttendAssist was built for it from day one.' },
    ],
    bullets: TRUST_BULLETS,
  },
  {
    slug: 'vs-paper-register',
    title: 'AttendAssist vs Paper Register - Digital Attendance Benefits',
    description: 'Compare AttendAssist vs paper attendance registers. Digital tracking saves time, prevents errors, and provides instant reports.',
    h1: 'AttendAssist vs paper register<br>Go digital, save time',
    sub: 'Paper registers have been around forever, but they have serious drawbacks. Here\'s why AttendAssist is better.',
    features: [
      { title: 'Never Lose Records', body: 'Paper: Gets lost, damaged, or worn out. AttendAssist: Records are always on your phone.' },
      { title: 'Instant Reports', body: 'Paper: Manual tallying of attendance. AttendAssist: Auto-generated monthly reports in one tap.' },
      { title: 'Search in Seconds', body: 'Paper: Flip through pages to find a record. AttendAssist: Search by name or date instantly.' },
      { title: 'Multiple Staff Types', body: 'Paper: Separate registers for different staff. AttendAssist: All staff in one app.' },
      { title: 'Data Portability', body: 'Paper: Records stay in the register. AttendAssist: Export data as CSV or JSON.' },
      { title: 'Environment Friendly', body: 'Paper: Uses paper. AttendAssist: Digital, no paper waste.' },
    ],
    bullets: TRUST_BULLETS,
  },
  {
    slug: 'vs-attendance-register-app',
    title: 'AttendAssist vs Other Attendance Register Apps - Comparison',
    description: 'Compare AttendAssist with other attendance register apps. See why AttendAssist is the best free offline attendance tracker.',
    h1: 'AttendAssist vs other<br>attendance register apps',
    sub: 'Most attendance apps focus on one use case. AttendAssist does four - attendance, payroll, rent, and classroom - plus 28 tools.',
    features: [
      { title: 'Multi-Purpose', body: 'Other apps: Attendance only. AttendAssist: Attendance, payroll, rent, classroom, and 28 financial tools.' },
      { title: 'Truly Free', body: 'Other apps: Freemium with ads or paid tiers. AttendAssist: Completely free, no ads, no subscriptions.' },
      { title: 'No Account', body: 'Other apps: Require sign-up. AttendAssist: No account, no email, no phone number needed.' },
      { title: 'Full Offline', body: 'Other apps: Limited offline. AttendAssist: Every feature works without internet.' },
      { title: 'Privacy-First', body: 'Other apps: Cloud sync with data on servers. AttendAssist: All data stays on your device.' },
      { title: 'Data Export', body: 'Other apps: Limited export options. AttendAssist: Full CSV and JSON export.' },
    ],
    bullets: TRUST_BULLETS,
  },
  {
    slug: 'vs-jibble',
    title: 'AttendAssist vs Jibble - Free Offline Attendance Alternative',
    description: 'Compare AttendAssist vs Jibble. See why AttendAssist is better for offline attendance tracking, household staff, and privacy.',
    h1: 'AttendAssist vs Jibble<br>A simpler, offline alternative',
    sub: 'Jibble is great for teams. AttendAssist is built for individuals managing household staff, tenants, and small businesses.',
    features: [
      { title: 'Offline-First', body: 'Jibble: Cloud-based with offline check-ins. AttendAssist: Fully offline, no servers at all.' },
      { title: 'Household Staff', body: 'Jibble: Business-focused. AttendAssist: Includes maid, cook, driver roles built in.' },
      { title: 'Rent & Tenant Tracking', body: 'Jibble: No rent management. AttendAssist: Track tenant rent and deposits.' },
      { title: 'Classroom Management', body: 'Jibble: No classroom features. AttendAssist: Student attendance and fee tracking.' },
      { title: 'Financial Tools', body: 'Jibble: No calculators. AttendAssist: 28 free financial calculators included.' },
      { title: 'Privacy', body: 'Jibble: Data stored on servers. AttendAssist: Data never leaves your device.' },
    ],
    bullets: TRUST_BULLETS,
  },
  {
    slug: 'vs-keka',
    title: 'AttendAssist vs Keka - Free Alternative for Small Business',
    description: 'Compare AttendAssist vs Keka. AttendAssist is free, offline, and perfect for small businesses and household staff management.',
    h1: 'AttendAssist vs Keka<br>Free, simpler, no bloat',
    sub: 'Keka is an enterprise HR platform. AttendAssist is a focused app for small teams, household staff, and personal management.',
    features: [
      { title: 'Pricing', body: 'Keka: Paid per employee per month. AttendAssist: Completely free, no payments ever.' },
      { title: 'Offline Use', body: 'Keka: Requires internet. AttendAssist: Works fully offline, no internet needed.' },
      { title: 'Household Staff', body: 'Keka: Enterprise HR only. AttendAssist: Manage maids, cooks, drivers, nannies.' },
      { title: 'Rent Tracking', body: 'Keka: No rent features. AttendAssist: Full tenant and rent management.' },
      { title: 'Setup Time', body: 'Keka: Onboarding and setup. AttendAssist: Install and start in 30 seconds.' },
      { title: 'Data Privacy', body: 'Keka: Cloud-based. AttendAssist: All data on your device.' },
    ],
    bullets: TRUST_BULLETS,
  },
  {
    slug: 'vs-spreadsheets',
    title: 'AttendAssist vs Spreadsheets - Better Than Google Sheets or Excel',
    description: 'Compare AttendAssist vs spreadsheets for attendance tracking. Dedicated app vs Google Sheets or Excel. See which is better.',
    h1: 'AttendAssist vs spreadsheets<br>Dedicated app wins',
    sub: 'Spreadsheets are flexible, but they are not designed for daily attendance tracking. Here\'s why AttendAssist is the better choice.',
    features: [
      { title: 'Optimized for Phones', body: 'Spreadsheets: Tiny cells, hard to use on mobile. AttendAssist: Built for phone-first daily use.' },
      { title: 'One-Tap Entry', body: 'Spreadsheets: Tap, type, navigate. AttendAssist: One tap to mark attendance.' },
      { title: 'No Formulas', body: 'Spreadsheets: You build formulas. AttendAssist: Reports generated automatically.' },
      { title: 'Structured Data', body: 'Spreadsheets: Easy to corrupt or misformat. AttendAssist: Clean, structured records.' },
      { title: 'Multi-Entity', body: 'Spreadsheets: Separate files or tabs. AttendAssist: Household, business, tenants, classroom in one app.' },
      { title: 'Export When Needed', body: 'Spreadsheets: Must use spreadsheet software. AttendAssist: Export to CSV when you need it.' },
    ],
    bullets: TRUST_BULLETS,
  },
];

// ─── Blog pages ────────────────────────────────────────────────────────────────

const BLOG_PAGES = [
  {
    slug: 'blog/how-to-track-maid-attendance',
    title: 'How to Track Maid Attendance - Best Methods & Free App',
    description: 'Learn how to track your maid\'s attendance effectively. From paper registers to free apps - find the best method for your home.',
    h1: 'How to track maid attendance<br>effectively',
    sub: 'From paper registers to digital apps - find the best way to track your maid\'s attendance and manage household staff.',
    features: [
      { title: 'Paper Register Method', body: 'Traditional paper registers work but are easy to lose and hard to search. Attendance must be tallied manually at month end.' },
      { title: 'Spreadsheet Method', body: 'Excel or Google Sheets works for tech-savvy users. Requires setup and manual data entry. Prone to accidental edits.' },
      { title: 'Dedicated App Method', body: 'Apps like AttendAssist are optimized for daily attendance. One-tap marking, auto-generated reports, and offline use make it the best option.' },
      { title: 'Why AttendAssist Works', body: 'Pre-configured maid role, daily check-in, monthly reports, salary tracking, and smart reminders. All offline and private.' },
    ],
    bullets: TRUST_BULLETS,
  },
  {
    slug: 'blog/how-to-manage-domestic-help',
    title: 'How to Manage Domestic Help - Complete Guide & Free App',
    description: 'Complete guide to managing domestic help: maids, cooks, drivers, and nannies. Track attendance, salary, and work records.',
    h1: 'How to manage domestic help<br>A complete guide',
    sub: 'Managing domestic staff requires tracking attendance, salary, and work history. Here\'s a practical guide to doing it right.',
    features: [
      { title: 'Track Attendance Daily', body: 'Mark daily attendance for each domestic helper. Note present, absent, leave, or holiday status consistently.' },
      { title: 'Maintain Salary Records', body: 'Keep clear records of salary paid, bonuses given, and advances taken. Prevents disputes and confusion.' },
      { title: 'Use Role-Based Profiles', body: 'Different roles have different expectations. Track maids, cooks, drivers, and nannies separately with role-appropriate settings.' },
      { title: 'Go Digital', body: 'Paper registers and memory are unreliable. Use a dedicated app like AttendAssist to maintain accurate, searchable records.' },
    ],
    bullets: TRUST_BULLETS,
  },
  {
    slug: 'blog/attendance-register-format',
    title: 'Attendance Register Format - Best Format for Staff & Students',
    description: 'Learn the best attendance register format for staff, students, and household workers. Free digital attendance register app included.',
    h1: 'Attendance register format<br>Best practices & templates',
    sub: 'The right format makes attendance tracking easy. Here\'s what to include and how AttendAssist handles it digitally.',
    features: [
      { title: 'Essential Columns', body: 'A good register needs: name, date, status (present/absent/leave), and notes. AttendAssist includes all of these.' },
      { title: 'Monthly Organization', body: 'Registers work best when organized by month. AttendAssist auto-generates monthly views with per-day status.' },
      { title: 'Status Options', body: 'Include all possible statuses: present, absent, leave, holiday, half-day, overtime. AttendAssist supports all six.' },
      { title: 'Digital Advantages', body: 'Digital registers never get lost, auto-calculate totals, and can be exported as CSV. AttendAssist provides all of this free.' },
    ],
    bullets: TRUST_BULLETS,
  },
  {
    slug: 'blog/employee-attendance-sheet',
    title: 'Employee Attendance Sheet - Free Template & Digital App',
    description: 'Free employee attendance sheet template and digital alternative. Track employee attendance with Excel or AttendAssist app.',
    h1: 'Employee attendance sheet<br>Template & digital solution',
    sub: 'Track employee attendance with a structured sheet or switch to a dedicated app. Here are both options.',
    features: [
      { title: 'Manual Sheet Template', body: 'Columns: employee name, date, in-time, out-time, status, notes. Works for small teams but requires manual effort.' },
      { title: 'Monthly Summary', body: 'Include present days, absent days, leave days, and overtime at the end of each month. AttendAssist auto-generates these.' },
      { title: 'Digital Alternative', body: 'Apps like AttendAssist replace attendance sheets entirely. One-tap marking, auto-reports, and zero setup.' },
      { title: 'Why Go Digital', body: 'No manual calculations, no lost sheets, instant search, CSV export for payroll. Free and offline.' },
    ],
    bullets: TRUST_BULLETS,
  },
  {
    slug: 'blog/how-to-track-rent-payments',
    title: 'How to Track Rent Payments - Free Rent Collection Guide',
    description: 'Learn how to track rent payments from tenants. Methods include spreadsheets, registers, and free apps like AttendAssist.',
    h1: 'How to track rent payments<br>A landlord\'s guide',
    sub: 'Keep track of who has paid rent and who hasn\'t. Simple methods for landlords of all types.',
    features: [
      { title: 'Paper Ledger', body: 'A simple notebook with tenant names and monthly columns. Low-tech but works. Downside: easy to lose or damage.' },
      { title: 'Spreadsheet', body: 'Excel or Google Sheets for digital tracking. Good for tech-savvy landlords but requires manual data entry.' },
      { title: 'Rent Tracking App', body: 'Apps like AttendAssist are built for this purpose. Record payments, track deposits, and view yearly summaries.' },
      { title: 'AttendAssist Advantages', body: 'Per-tenant payment history, security deposit tracking, yearly summaries, CSV export for tax filing. All free and offline.' },
    ],
    bullets: TRUST_BULLETS,
  },
  {
    slug: 'blog/how-to-manage-tenants',
    title: 'How to Manage Tenants - Complete Guide for Landlords',
    description: 'Complete guide to managing tenants: rent collection, security deposits, payment tracking, and communication. Free tools included.',
    h1: 'How to manage tenants<br>A complete guide for landlords',
    sub: 'From rent collection to deposit management - practical advice for landlords managing rental properties.',
    features: [
      { title: 'Track Rent Payments', body: 'Record monthly payments consistently. Note the date, amount, and payment method for each transaction.' },
      { title: 'Manage Security Deposits', body: 'Track deposit amounts, collection dates, and return status. Keep this data linked to each tenant.' },
      { title: 'Maintain Tenant Records', body: 'Store tenant contact information, lease dates, rent amounts, and important notes in one place.' },
      { title: 'Go Digital with AttendAssist', body: 'AttendAssist provides dedicated tenant profiles, rent payment tracking, deposit management, and exportable records. Free and offline.' },
    ],
    bullets: TRUST_BULLETS,
  },
  {
    slug: 'blog/how-to-track-student-attendance',
    title: 'How to Track Student Attendance - Best Methods for Teachers',
    description: 'Learn effective methods for tracking student attendance. From paper registers to free apps, find what works for your classroom.',
    h1: 'How to track student attendance<br>Methods for every classroom',
    sub: 'Track student attendance efficiently with the right tools and methods. Whether you teach 5 students or 50.',
    features: [
      { title: 'Paper Register', body: 'Traditional method. Students sign in or teacher marks. Works but is time-consuming and records can be lost.' },
      { title: 'Spreadsheet Tracking', body: 'Digital register in Excel or Sheets. Better organization but still requires manual entry and formula setup.' },
      { title: 'Bulk Attendance Apps', body: 'Apps like AttendAssist let you mark the entire class at once. One tap for all students, then adjust individually if needed.' },
      { title: 'Why AttendAssist Works', body: 'Bulk attendance marking, roll number support, per-student reports, fee tracking integration. Designed for tutors and coaches.' },
    ],
    bullets: TRUST_BULLETS,
  },
  {
    slug: 'blog/how-to-manage-coaching-center',
    title: 'How to Manage a Coaching Center - Operations Guide & Free App',
    description: 'Learn how to manage a coaching center efficiently. Student attendance, fee collection, and class management tips with free tools.',
    h1: 'How to manage a coaching center<br>Operations & tools guide',
    sub: 'Running a coaching center means managing students, attendance, fees, and schedules. Here\'s how to do it efficiently.',
    features: [
      { title: 'Student Attendance', body: 'Mark attendance for each batch or class. Track individual student attendance over time.' },
      { title: 'Fee Collection', body: 'Record tuition fee payments per student. Track who has paid and who hasn\'t on a monthly basis.' },
      { title: 'Student Records', body: 'Maintain student profiles with name, roll number, class, contact, and attendance history.' },
      { title: 'AttendAssist for Coaches', body: 'Bulk attendance, fee tracking, roll numbers, and exportable reports. Built for coaching centers.' },
    ],
    bullets: TRUST_BULLETS,
  },
  {
    slug: 'blog/payroll-for-small-business',
    title: 'Payroll for Small Business - Simple Payroll Management Guide',
    description: 'Simple payroll management guide for small businesses. Track employee salaries, payments, and attendance without expensive software.',
    h1: 'Payroll for small business<br>Simple management guide',
    sub: 'Manage employee payroll without expensive HR software. Practical advice for small business owners.',
    features: [
      { title: 'Track Employee Salaries', body: 'Record salary amounts per employee. Keep a clear record of base pay, bonuses, and deductions.' },
      { title: 'Maintain Payment History', body: 'Log every payment with date and amount. Searchable history prevents disputes and helps with tax filing.' },
      { title: 'Link Attendance to Payroll', body: 'Attendance records provide context for payroll. See if absences or overtime affected payments.' },
      { title: 'AttendAssist for Payroll', body: 'Free payroll tracking with attendance integration. Salary records, payment history, and CSV export.' },
    ],
    bullets: TRUST_BULLETS,
  },
  {
    slug: 'blog/best-offline-attendance-app',
    title: 'Best Offline Attendance App - 2026 Comparison & Review',
    description: 'Looking for the best offline attendance app? Compare features, pricing, and privacy. AttendAssist leads in offline attendance tracking.',
    h1: 'Best offline attendance app<br>2026 comparison',
    sub: 'Compare the top offline attendance apps. We evaluated features, privacy, pricing, and ease of use.',
    features: [
      { title: 'What to Look For', body: 'Full offline support, no account required, privacy, ease of use, data export, and multiple tracking options.' },
      { title: 'Top Pick: AttendAssist', body: 'AttendAssist offers full offline support, no account needed, zero data collection, and household + business + tenant + classroom tracking.' },
      { title: 'Key Advantages', body: 'Free, no ads, no subscriptions, 28 calculators included, CSV/JSON export, smart reminders, 40 pre-configured roles.' },
      { title: 'Who It\'s For', body: 'Households with domestic staff, small businesses, landlords, tutors, and coaching centers.' },
    ],
    bullets: TRUST_BULLETS,
  },
];

// ─── Export all pages ─────────────────────────────────────────────────────────

module.exports = [
  ...CORE_PAGES.map(p => ({ ...p, category: 'general' })),
  ...HOUSEHOLD_PAGES.map(p => ({ ...p, category: 'household' })),
  ...ATTENDANCE_PAGES.map(p => ({ ...p, category: 'attendance' })),
  ...PAYROLL_PAGES.map(p => ({ ...p, category: 'payroll' })),
  ...TENANT_PAGES.map(p => ({ ...p, category: 'tenants' })),
  ...CLASSROOM_PAGES.map(p => ({ ...p, category: 'classroom' })),
  ...BUSINESS_PAGES.map(p => ({ ...p, category: 'business' })),
  ...TOOL_PAGES.map(p => ({ ...p, category: 'tools' })),
  ...COMPARISON_PAGES.map(p => ({ ...p, category: 'comparison' })),
  ...BLOG_PAGES.map(p => ({ ...p, category: 'blog' })),
];
