name: Deploy to GitHub Pages (Main Branch Root)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build the project
        run: npm run build

      - name: Deploy to root of main
        run: |
          # Allow advanced glob patterns
          shopt -s extglob
          
          # Clean all except .git, .github, and dist
          find . -maxdepth 1 ! -name '.' ! -name '.git' ! -name '.github' ! -name 'dist' -exec rm -rf {} +

          # Move built files to root
          cp -r dist/* .
          rm -rf dist

          # Commit and push
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git diff --quiet || git commit -m "Deploy build to root"
          git push
