name: Deploy to GitHub Pages (Main Branch Root)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy to root
        run: |
          shopt -s extglob
          rm -rf !(.git|.github|dist)
          cp -r dist/* .
          rm -rf dist
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git diff --quiet || git commit -m "Deploy to root"
          git push
